# Generated by Django 2.0.2 on 2018-03-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRCSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=0)),
                ('oauth_token', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
            ],
        ),
    ]
